# This is the configuration used to check the `Middleman::Wundertuete` source code.

# Configuration
# =============

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/FileName:
  Description: 'Use snake_case for source file names.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#snake-case-files'
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Description: >-
                 Checks that exactly one space is used between a method name and the first argument for method calls
                 without parentheses.
  Enabled: false

Style/TrailingBlankLines:
  Description: 'Checks trailing blank lines and final newline.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#newline-eof'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters with 10 characters as buffer.'
  Max: 130